spring:
  config:
    import: "optional:file:${HOME}/props/local-apic.yaml"
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${fr.insee.apic.auth-server-url}"

server:
  http2:
    enabled: true
  tomcat:
    accesslog:
      enabled: true
      directory: "${HOME}/logs"
fr:
  insee:
    apic:
      security:
        csrf:
          disable: false
        public-endpoints: "/init, /healtcheck"
      interface-controllers:
        package: "fr.insee.myapp.parent_package_of_controllers"
      backend:
        url: "http://myapp.insee.fr"
      cors:
        allowed-origins: "http://myapp-client.insee.fr"

jwt:
  role-claim:
    key: "realm_access"
    roles: "roles"
  id-claim: "preferred_username"
